export enum AuthStatus {
  NONE = 'NONE',
  AUTHENTICATING = 'AUTHENTICATING',
  AUTHENTICATED = 'AUTHENTICATED',
  AUTHENTICATION_ERROR = 'AUTHENTICATION_ERROR',
  DISCONNECTING = 'DISCONNECTING',
  DISCONNECTED = 'DISCONNECTED',
  DISCONNECTION_ERROR = 'DISCONNECTION_ERROR',
}

export enum SocketStatus {
  NOT_CONNECTED = 'NOT_CONNECTED',
  CONNECTING = 'CONNECTING',
  CONNECTED = 'CONNECTED',
  CONNECTION_ERROR = 'CONNECTION_ERROR',

  CONNECTION_WAIT = 'CONNECTION_WAIT',
  CONNECTION_LOST = 'CONNECTION_LOST',
}

export enum SortDirections {
  NONE = 'NONE',
  ASCENDING = 'ASCENDING',
  DESCENDING = 'DESCENDING',
}

export enum ThreadType {
  DIRECT = 'DIRECT',
  GROUP = 'GROUP',
  CHANNEL = 'CHANNEL',
}

export enum RequestState {
  NEVER = 'NEVER',
  FETCHING_FIRST = 'FETCHING_FIRST',
  FETCHING = 'FETCHING',
  SUCCESS = 'SUCCESS',
  FAILURE = 'FAILURE',
  OUTDATED = 'OUTDATED',
}

export enum UserStatus {
  AWAY = 'AWAY',
  ONLINE = 'ONLINE',
  OFFLINE = 'OFFLINE',
}

export enum Keys {
  ESCAPE = 'Escape',
  ENTER = 'Enter',
}
