export enum AuthStatus {
  NONE = 'NONE',
  AUTHENTICATING = 'AUTHENTICATING',
  AUTHENTICATED = 'AUTHENTICATED',
  AUTHENTICATION_ERROR = 'AUTHENTICATION_ERROR',
  DISCONNECTING = 'DISCONNECTING',
  DISCONNECTED = 'DISCONNECTED',
  DISCONNECTION_ERROR = 'DISCONNECTION_ERROR',
}

export enum SocketStatus {
  NOT_CONNECTED = 'NOT_CONNECTED',
  CONNECTING = 'CONNECTING',
  CONNECTED = 'CONNECTED',
  CONNECTION_ERROR = 'CONNECTION_ERROR',
  CONNECTION_LOST = 'CONNECTION_LOST',
}

export enum SortDirections {
  NONE = 'NONE',
  ASCENDING = 'ASCENDING',
  DESCENDING = 'DESCENDING',
}

export enum RequestState {
  NEVER = 'NEVER',
  FETCHING = 'FETCHING',
  SUCCESS = 'SUCCESS',
  FAILURE = 'FAILURE',
}

export enum UserStatus {
  AWAY = 'AWAY',
  ONLINE = 'ONLINE',
  OFFLINE = 'OFFLINE',
}
